# Generated by Django 2.1.2 on 2018-10-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LabBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=512)),
                ('is_pdf', models.BooleanField()),
                ('content_descr', models.TextField()),
                ('date_issued', models.DateField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('index_added_pr_file', models.BooleanField()),
                ('index_no_pages', models.IntegerField()),
                ('doc_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docindex.DocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('room_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=512)),
                ('is_pdf', models.BooleanField()),
                ('alias', models.CharField(max_length=512)),
                ('content_descr', models.TextField()),
                ('vol_no', models.IntegerField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('date_archived', models.DateField()),
                ('doc_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docindex.DocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=512)),
                ('is_pdf', models.BooleanField()),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('IND', 'In draft'), ('COM', 'Complete')], default='', max_length=3)),
                ('sign_date', models.DateField()),
                ('is_filed', models.BooleanField()),
                ('doc_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docindex.DocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=512)),
                ('is_pdf', models.BooleanField()),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('IND', 'In draft'), ('COM', 'Complete')], default='', max_length=3)),
                ('sign_date', models.DateField()),
                ('is_filed', models.BooleanField()),
                ('doc_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docindex.DocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='studyplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docindex.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docindex.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='study_plan',
            field=models.ManyToManyField(to='docindex.StudyPlan'),
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docindex.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docindex.User'),
        ),
        migrations.AddField(
            model_name='labbook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docindex.User'),
        ),
    ]
