# Generated by Django 2.1.2 on 2018-10-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docindex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.User'),
        ),
    ]
