# Generated by Django 2.1.2 on 2018-10-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docindex', '0003_auto_20181014_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docindex.Project'),
        ),
    ]
