# Generated by Django 2.1.2 on 2018-10-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docindex', '0004_auto_20181014_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbook',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Location'),
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Location'),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Location'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Location'),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Project'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docindex.Project'),
        ),
    ]
