# Generated by Django 2.1.2 on 2018-10-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('SP', 'Study plan'), ('R', 'Report'), ('RDF', 'Related file'), ('LBN', 'Lab book')], default='', max_length=3)),
                ('e_copy', models.FileField(upload_to='uploads/')),
                ('content_descr', models.TextField()),
                ('date_issued', models.DateField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('index_added_pr_file', models.BooleanField()),
                ('index_no_pages', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('room_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(max_length=8)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('SP', 'Study plan'), ('R', 'Report'), ('RDF', 'Related file'), ('LBN', 'Lab book')], default='', max_length=3)),
                ('e_copy', models.FileField(upload_to='uploads/')),
                ('alias', models.CharField(max_length=512)),
                ('content_descr', models.TextField()),
                ('vol_no', models.IntegerField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('date_archived', models.DateField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('SP', 'Study plan'), ('R', 'Report'), ('RDF', 'Related file'), ('LBN', 'Lab book')], default='', max_length=3)),
                ('e_copy', models.FileField(upload_to='uploads/')),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('IND', 'In draft'), ('COM', 'Complete')], default='', max_length=3)),
                ('sign_date', models.DateField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(choices=[('SP', 'Study plan'), ('R', 'Report'), ('RDF', 'Related file'), ('LBN', 'Lab book')], default='', max_length=3)),
                ('e_copy', models.FileField(upload_to='uploads/')),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('IND', 'In draft'), ('COM', 'Complete')], default='PEN', max_length=3)),
                ('sign_date', models.DateField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='study_plan',
            field=models.ManyToManyField(to='fileindex.StudyPlan'),
        ),
        migrations.AddField(
            model_name='labbook',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Location'),
        ),
        migrations.AddField(
            model_name='labbook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileindex.Project'),
        ),
    ]
