# Generated by Django 2.1.2 on 2018-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbook',
            name='content_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='index_no_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='content_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='date_archived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='vol_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='sign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
