# Generated by Django 2.1.2 on 2018-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0003_auto_20181020_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('IND', 'In draft'), ('COM', 'Complete')], default='PEN', max_length=3),
        ),
    ]
