# Generated by Django 2.1.2 on 2018-11-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileindex', '0006_auto_20181113_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='document_code',
        ),
        migrations.RemoveField(
            model_name='report',
            name='e_copy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
    ]
